### ISSUE TITLE
Getting error "Response limit exceeded for your plan. Upgrade to access more responses through the SDK" 

### ISSUE THREAD

**Issue by youvalv** [SurveyMonkey/surveymonkey-ios-sdk#10]
I have an upgraded account, I can get individual responses through the "Analyze results" section on SurveyMonkey website. Keep getting this error on iOS and Android (Sample survey hash works fine)

When accessed support@surveymonkey.com they referenced me to open an issue in github :)

**Comment by benleiken** [comment]
@youvalv Can you tell me what type of plan you have? Select, Gold, or Platinum?

**Comment by benleiken** [comment]
@youvalv Just so you know, the in-app SDK data export feature is only for Gold and Platinum accounts. you can use the SDK to display surveys on Basic and Select accounts, you just won't have access to the respondent data. If you have a Gold or Platinum account, let me know and I'll reopen this.

**Comment by youvalv** [comment]
I understand, It's not clear from the documentation. I have SELECT plan

thanks!

**Comment by benleiken** [comment]
@youvalv I've updated the [docs](https://github.com/SurveyMonkey/surveymonkey-ios-sdk#important-consideration) to make it clearer -- feel free to submit a PR on the README if you think the docs could be improved!
