### ISSUE TITLE
Survey response error log

### ISSUE THREAD

**Issue by Govindakarthikeyan** [SurveyMonkey/surveymonkey-ios-sdk#12]
Hello,

I couldn't handle the survey response in my iOS App. I am getting the following error log,

Error Domain=SurveyMonkeySDK_ServerError Code=5 "(null)" UserInfo={SurveyMonkeySDK_Error=There was a problem retrieving the user's response to this survey., NSUnderlyingError=0x160a40500 {Error Domain=SurveyMonkeySDK_ServerError Code=7 "(null)" UserInfo={SurveyMonkeySDK_Error=Response limit exceeded for your plan. Upgrade to access more responses through the SDK.}}}

May I have a solution to the above issue

**Comment by benleiken** [comment]
@Govindakarthikeyan  Just so you know, the in-app SDK data export feature is only for Gold and Platinum accounts. you can use the SDK to display surveys on Basic and Select accounts, you just won't have access to the respondent data. If you have a Gold or Platinum account, let me know and I'll reopen this.

**Comment by Govindakarthikeyan** [comment]
Thanks benleiken for your swift response.
