### ISSUE TITLE
Survey response validation

### ISSUE THREAD

**Issue by Govindakarthikeyan** [SurveyMonkey/surveymonkey-ios-sdk#13]
Hello,

For response validation, I have the delegate method as,
- (void)respondentDidEndSurvey:(SMRespondent *)respondent error:(NSError *) error {
}

Since I am using the select plan(couldn't upgrade to the Gold or Silver plan because of finance issues) on the Survey monkey, I will always get the error(code 7) as "Response limit exceeded for your plan. Upgrade to access more responses through the SDK." But I can see the responses in the Result analytics in the backend site.

My query: Can I assume the response is the success if the error code is 7 or the respondent is not nil?

**Comment by benleiken** [comment]
@Govindakarthikeyan Yes, you can assume it's a successful submission. You don't even need to implement the respondentDidEndSurvey: delegate method if you don't have a Gold/Platinum account since it's only used to parse respondents and errors. It's up to you.

**Comment by PaulTaykalo** [comment]
@benleiken What about other types of errors? like internet issue or Response Limit reached errors?

**Comment by benleiken** [comment]
@PaulTaykalo connectivity and response limit reached errors are returned in the respondentDidEndSurvey delegate method. You can ignore the response limit reached error if you're on a basic or select plan and aren't interested in parsing responses in real time -- see Govindakarthikeyan's post above
