### ISSUE TITLE
Xcode 7 build warnings due to local file references

### ISSUE THREAD

**Issue by ted-ah** [SurveyMonkey/surveymonkey-ios-sdk#14]
When building an app using the SurveyMonkey iOS SDK in Xcode 7.3.1, I see several build warnings during the .dSYM generation step. It appears that it's trying to reference some local files.

This can be reproduced by building the sample app (SimpleSurvey) that's in this repo using Xcode 7.3.1.  See screenshot below of output of build warnings.

<img width="922" alt="screen shot 2016-06-29 at 9 46 13 am" src="https://cloud.githubusercontent.com/assets/13276320/16460907/a2d76b02-3dde-11e6-9b15-8e15c3acfa78.png">

**Comment by benleiken** [comment]
@ted-ah just fixed this issue in 1.0.6 -- thanks for reporting!
