### ISSUE TITLE
Xcode 7 build warnings with v1.0.7 of SDK

### ISSUE THREAD

**Issue by ted-ah** [SurveyMonkey/surveymonkey-ios-sdk#15]
Hi @benleiken, thanks for taking a look at issue #14. I just updated to the latest version of the SurveyMonkey SDK (v1.0.7), but am still seeing the same build warnings referenced in issue #14. Would you mind taking another look? I was still able to reproduce it using the Simple Survey sample app. Thanks!

<img width="922" alt="screen shot 2016-07-01 at 10 04 30 am" src="https://cloud.githubusercontent.com/assets/13276320/16528873/50aed65c-3f74-11e6-8b6b-2f53f428695f.png">

**Comment by benleiken** [comment]
@ted-ah rats. try again with 1.0.8 -- think i found the pesky flag

**Comment by ted-ah** [comment]
@benleiken Build warnings are now gone in 1.0.8. Thanks!
