### ISSUE TITLE
Setting Collector Variables

### ISSUE THREAD

**Issue by chrismoisan** [SurveyMonkey/surveymonkey-ios-sdk#19]
Hi. I see from docs that the SDK allows you to set Time or Event based collection/ sampling e.g "Set time intervals to show surveys to users. For example, show a survey a certain amount of time after an app install"

Can you please confirm  how/where you set the time/events that triggers the survey?
 
Is this embedded in the app code? or can these variables be changed remotely via our account on Surveymonkey.com?
e.g. we'd like to say try setting a survey to appear on 6th time they open the app. We'd also like to test setting this variable to 2nd time to see how this affects responses and we want to run these tests without having to change/resubmit the app
 
Please can you confirm how this is done and ideally provide some documentation/ point us to the documentation for this  as we can't find this. Thnx

**Comment by benleiken** [comment]
Hey @chrismoisan, the feature you're referencing is our ["Intercept Modal" ](https://github.com/SurveyMonkey/surveymonkey-ios-sdk#the-intercept-modal). The timing logic for this modal must be embedded in the app and can't be controlled via surveymonkey.com. [This](http://surveymonkey.github.io/surveymonkey-ios-sdk/Classes/SMFeedbackViewController.html#//api/name/scheduleInterceptFromViewController:alertTitle:alertBody:positiveActionTitle:cancelTitle:afterInstallInterval:afterAcceptInterval:afterDeclineInterval:) is the API for configuring an intercept survey. It's all timing driven, so you can't specify a # of times post-install to wait to display the survey.

If the intercept doesn't fit your needs, you can just use the [regular](http://surveymonkey.github.io/surveymonkey-ios-sdk/Classes/SMFeedbackViewController.html#//api/name/presentFromViewController:animated:completion:) survey presentation API and create your own set of conditions determining when/when not to display the survey -- e.g. # of times app has been opened, etc.

Hope I've been helpful, feel free to follow up!
