### ISSUE TITLE
Survey Hash

### ISSUE THREAD

**Issue by rpwilsonrph** [SurveyMonkey/surveymonkey-ios-sdk#2]
Survey Link: https://www.surveymonkey.com/s/N352GFB We are signed up as a beta user. The view controller (SMFeedbackViewController) fails with the following error when we attempt to use our survey. It works correctly when you use the demo survey provided by SurveyMonkey. *** Terminating app due to uncaught exception \'NSRangeException\', reason: \'*** -[__NSCFString substringFromIndex:]: Index 9223372036854775807 out of bounds; string length 25753\'.

I suspect we don't have the mobile collector set up correctly. I am using N352GFB as the hash. Can you provide me with some info on setting up the mobile collector. The error may be my misunderstanding of the link between SMFeedbackViewController and the collector.

**Comment by benleiken** [comment]
@rpwilsonrph we haven't started adding new users to the beta -- if you filled out the Wufoo form, that means you're on our list and we'll be contacting you when we open up the beta. Until that time, the SDK unfortunately won't work for you as it needs to be configured using an SDK collector. We'll be in touch soon!

**Comment by rpwilsonrph** [comment]
Ben —

Thanks for the followup. We are probably going to the App Store next week so we will back SurveyMonkey out of the project. Maybe we can begin using it in the next rev of the product.

Too bad. We would love to have had feedback in this rev.

Please let me know when you can include us.

Paul

**Comment by benleiken** [comment]
@rpwilsonrph Better late than never (I hope), we are soft launching today! Docs have been updated, but feel free to reach out and let me know if I can be of help.
