### ISSUE TITLE
ATS exceptions won't be allowed as of January 2017

### ISSUE THREAD

**Issue by jaz-ah** [SurveyMonkey/surveymonkey-ios-sdk#20]
right now survey monkey requires this exception, but in ~2 months this won't be allowed anymore by Apple - just want to see what kind of progress is being made on the server side and when we should expect to be able to remove this:

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
      <key>api.surveymonkey.net</key>
      <dict>
        <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
        <false/>
      </dict>
    </dict>
</dict>

**Comment by benleiken** [comment]
@jaz-ah -- as of November 1st, this current requirement will no longer be necessary and you should be able to omit the NSExceptionDomains key(s) from your .plist. If you have any trouble, feel free to reopen this. Thanks!

**Comment by jaz-ah** [comment]
ok thanks @benleiken
