### ISSUE TITLE
Final survey page is displayed after completing the survey

### ISSUE THREAD

**Issue by Aranda** [SurveyMonkey/surveymonkey-ios-sdk#22]
After pressing the final DONE button and submitting the survey, a loading page is displayed, however this loading page is dismissed very quickly revealing the final survey page again. The user is able to scroll the page for a few seconds before the View Controller is finally dismissed, returning control the the app.

Is this something that can be worked around in the construction of the Survey itself, or an issue that can be resolved inside the SDK?

**Comment by benleiken** [comment]
@Aranda apologies for the delay. we are looking into this and will address in our next update -- coming soon.
