### ISSUE TITLE
Checking if the user has completed the survey

### ISSUE THREAD

**Issue by drinkius** [SurveyMonkey/surveymonkey-ios-sdk#24]
I'm using iOS SDK to collect responses and would like to be able to check if the user has completed the survey or not to update UI accordingly. I tried setting up the callback for survey:

```
- (void)respondentDidEndSurvey:(SMRespondent *)respondent error:(NSError *) error {
}
```

but I always get respondent == nil and error: SMError * domain: nil - code: 5

From what I've read on StackOverflow and GitHub issue tracker - it might mean that the account isn’t on Platinum plan and doesn’t have access to respondent data, however - we are on Platinum plan.

Could you please tell me how to set up the callback so that we can check if the response been collected or not?

**Comment by larryonoff** [comment]
Any updates on this issue?

**Comment by benleiken** [comment]
@larryonoff @drinkius apologies for the delay: this definitely sounds like a bug: can you fill out this survey so we can better assist each of you? https://www.surveymonkey.com/r/2FCVR87

**Comment by benleiken** [comment]
closing, since no responses to the survey were received

**Comment by larryonoff** [comment]
SurveyMonkey feedback is really ridiculous.

1. We've been redirected to github by the support team.
2. We haven't been provided with any feedback for several weeks.

So we finished the project with known unresolved issue and hope stopped using SurveyMonkey.
