### ISSUE TITLE
How to integrate with React Native?

### ISSUE THREAD

**Issue by rebelliard** [SurveyMonkey/surveymonkey-ios-sdk#26]
I'm a JavaScript developer new to mobile, and I was wondering if there was a guide people like could use in order to ingrate their RN apps with surveymonkey?

**Comment by benleiken** [comment]
@rebelliard unfortunately we don't have a RN-specific guide. the steps to integrate shouldn't differ too much. if you've been successful -- we'd very much appreciate a PR to our documentation with any tips for others!

**Comment by onmyway133** [comment]
@rebelliard Hi, you can do like this https://github.com/onmyway133/notes/issues/464

**Comment by yarikpwnzer** [comment]
https://github.com/yarikpwnzer/react-native-survey-monkey
