### ISSUE TITLE
Response limit exceeded with Gold plan

### ISSUE THREAD

**Issue by SchallerJe** [SurveyMonkey/surveymonkey-ios-sdk#27]
Dear SurveyMonkey team, 
when using the iOS SDK, I get the following error: 
"Optional(Error Domain=SurveyMonkeySDK_ServerError Code=5 \"(null)\" UserInfo={SurveyMonkeySDK_Error=There was a problem retrieving the user\'s response to this survey., NSUnderlyingError=0x1139dbaf0 {Error Domain=SurveyMonkeySDK_ServerError Code=7 \"(null)\" UserInfo={SurveyMonkeySDK_Error=Response limit exceeded for your plan. Upgrade to access more responses through the SDK.}}})" 

But we already have the Gold plan and this shouldn't happen. Could you please help? 

Regards, 
Jens

**Comment by ukmarn** [comment]
@SchallerJe I am getting the same error with free plan, even though I haven't responded to the survey more that 5 times in total! Looks like there is something wrong with the SDK (among many other bugs).

**Comment by benleiken** [comment]
@SchallerJe apologies for the delay -- can you fill this out?  https://www.surveymonkey.com/r/2FCVR87

You shouldn't be receiving error code 7 if you're on a gold plan. I'm also not sure why you're seeing two error codes at once (5 +7). You appear to be using the SDK in a Swift project -- is that correct?

**Comment by benleiken** [comment]
@ukmarn You should be receiving error code 7 since you're on a Free plan. We don't allow Free users to parse SDK responses, so you'll always receive error code 7. The only change we're making to this in the next version of the SDK is a better error message!

Can you elaborate on the "many other bugs" you're seeing? Please open additional issues and we can try to help resolve them.

**Comment by ukmarn** [comment]
@benleiken What is the limit for the free plan? I am getting same errors inside my swift project and I only have around 20 responses to the survey.
Also the `respondent` object inside `respondentDidEndSurvey` is always empty.

**Comment by ukmarn** [comment]
@benleiken Thank you for such a quick response.
That makes more sense then - I saw somewhere that there is a limit of 100 responses for each survey, that's why it made no sense to me why am I getting all the errors.

**Comment by benleiken** [comment]
@ukmarn Of course! 

Yes, the 100 response limit refers to total responses collected on the survey. We'll update our error message to make things less confusing.

**Comment by SchallerJe** [comment]
@benleiken Actually I made a mistake by thinking that we got the Gold plan. We actually have the Select plan. But anyways: Even in the Select plan it says that we have unlimited responses. Sadly you can't even use the SDK with the Select plan because you always get the "response limit exceeded" error. At least that's what the SurveyMonkey support told me.

**Comment by benleiken** [comment]
@SchallerJe easy mistake to make -- we have a overall respondent limit for our basic accounts and then a separate limitation for the SDK that affects Basic and Select accounts

**Comment by SchallerJe** [comment]
Sadly, yes. And that is one of the reasons why we will abandon SurveyMonkey for something clearer, more user friendly and more usable.
