### ISSUE TITLE
Schedule Intercept method doesn't work

### ISSUE THREAD

**Issue by chrisjf** [SurveyMonkey/surveymonkey-ios-sdk#31]
According to the [documentation](https://surveymonkey.github.io/surveymonkey-ios-sdk/Classes/SMFeedbackViewController.html), the method `scheduleInterceptFromViewController:alertTitle:alertBody:positiveActionTitle:cancelTitle:afterInstallInterval:afterAcceptInterval:afterDeclineInterval:` should schedule an alert according to the variables passed.

I put 30 seconds for the `afterInstallInterval` parameter, and **nothing happens** after 30 seconds. 

Only after I quit and relaunch the app does the UIAlertView appear. 

This behavior should be either:

- accurately documented, or
- fixed.

**Comment by benleiken** [comment]
addressed in latest release. apologies for the delay
