### ISSUE TITLE
Open Source the SDK

### ISSUE THREAD

**Issue by chrisjf** [SurveyMonkey/surveymonkey-ios-sdk#33]
This repository has an open source license associated with it (MIT) but the actual framework `SurveyMonkeyiOSSDK.framework` is private.

Considering there are more and more high profile cases of apps doing sketchy things privacy-wise ([Uber's Greyball](https://www.nytimes.com/2017/03/03/technology/uber-greyball-program-evade-authorities.html), [AccuWeather](https://daringfireball.net/linked/2017/08/22/strafach-accuweather), etc.), open-sourcing the SurveyMonkey SDK would go a long way to build trust. 

Many development teams now refuse to include closed-source SDKs in their apps because they cannot guarantee the SDKs' behavior. Making the SDK open-source proves this unequivocally.

**Comment by benleiken** [comment]
@chrisjf these are certainly valid concerns but because our SDK uses private APIs, we're unable to open source it at the moment. we'll certainly consider an open source addition in future iterations of the SDK!
