### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Logician** [SurveyMonkey/surveymonkey-ios-sdk#41]
Every time an SMFeedbackViewController is created (and dismissed) it is retained in memory along with several megabytes of dependencies (WebKit etc). We are using ARC.

This makes it unusable to use in our game which wants to be able to show several different surveys.
We hope to get an answer as soon as possible as it may influence whether we will end up using SurveyMonkey or not.

**Comment by benleiken** [comment]
@Logician is the issue too many strong references here? from the interface:
```
@interface SMFeedbackViewController ()<UIWebViewDelegate>
@property (nonatomic, strong) UIWebView *webView;
@property (nonatomic, strong) UIViewController * presentingVC;
@end
```

**Comment by Logician** [comment]
You can debug this with the "Debug Memory Graph" button in Xcode when you have the application running. There could be some self-referencing code blocks that have a retain-cycle perhaps? It's basically not SMFeedbackViewController holding strong references, it's other things holding a reference to the SMFeedbackViewController instance. If you could debug this by trying to release the reference in a sample code app that would be great. Also by creating a new SMFeedbackViewController instance after it's been dismissed should show in that Xcode debugger as several SMFeedbackViewController instances staying in memory.

**Comment by Logician** [comment]
It could also be the viewcontroller registering for a notifications and then not unregistering in for example viewWillDisappear or viewDidDisappear..

**Comment by benleiken** [comment]
@Logician fussed with this a bit and for all of my efforts, couldn't eliminate the retain cycle. 
<img width="443" alt="screen shot 2018-02-27 at 10 51 31 pm" src="https://user-images.githubusercontent.com/1434562/36773932-dfa98aee-1c10-11e8-969c-5511c696ed4c.png"> No matter what I do, the internal UIWebView's delegate always seems to reference the SMFeedbackController. Tried explicitly nullifying the delegate on dealloc, dismiss, viewDidDisappear, etc.

Did a bit of digging and found this (old) article -- seems like uiwebviews have memory issues generally.

Unless you've got any other suggestions, might need to put this one on the back burner for now.

**Comment by Logician** [comment]
A couple of suggestions:
- Could try to look into WKWebView which seems to be what Apple recommends to use
- Could try to just reuse SMFeedbackController by adding functionality to it to switch it to another survey ID so we can present it again
- Could let me have a look at your source if we can work something out, as long as it's viable for us to use then we can purchase a plan (chicken & egg problem)
- I could write my own WKWebView implementation still using SurveyMonkey URLs and attempt to get that going with perhaps some help on hooking into the webview to know when it's been completed.

**Comment by benleiken** [comment]
@Logician of course! wish I could be much more helpful, but the team is slammed right now.

Yeah, why not try re-initializing the SMFeedbackViewController with a different survey hash and presenting it again? Does that help at all?

We definitely plan to switch to WKWebViews -- we're long overdue for a significant update to the SDK.

I'm open to sharing source, but there's red tape involved... so not ideal.

**Comment by Logician** [comment]
I can't just call initWithSurvey again, just tried that and it crashed after the 3rd try with "Message from debugger: Terminated due to memory issue", when recreating them entirely I can get in 5/6 retries before getting killed due to memory issues.

To do it cleanly, SMFeedbackViewController needs a new function to set a survey ID and as a whole needs to be checked if the code and the state it keeps is good for re-use, which that new function could help ensure.

In the mean time I'll try to implement it myself with WKWebView and will let you know how it goes..

**Comment by Logician** [comment]
This works for us: [SurveyMonkey.txt](https://github.com/SurveyMonkey/surveymonkey-ios-sdk/files/1793997/SurveyMonkey.txt)
So I highly recommend you start using WkWebView. 
What we currently lack, is knowing whether the user answered all questions or not, due to your private API..

**Comment by benleiken** [comment]
@Logician wow. thanks for going to all of that trouble. this is great. no promises, but if I can find time in the next 2 weeks to add in the remaining functionality, i'll push a new major version of the SDK. will let you know here when i do. again, thank you!

**Comment by Logician** [comment]
Hey Ben, did you have a chance to look into it yet?
Thanks, Jeffrey

**Comment by benleiken** [comment]
@Logician apologies -- I have not forgotten, just haven't had time yet -- we're working on a separate launch. I'm hoping to dive in for a few hrs next weekend and knock it out

**Comment by benleiken** [comment]
@Logician just pushed a new update (2.0.0 -- because I dropped iOS 7 support thx to WKWebviews). Memory leak issue appears resolved. Let me know how it works for you! Closing this for now
