### ISSUE TITLE
Linker error with release 2.0.2

### ISSUE THREAD

**Issue by doctorcolinsmith** [SurveyMonkey/surveymonkey-ios-sdk#47]
I just upgraded my project to 2.0.2 and received the following linker error (paths are scrubbed for privacy).  It appears that the binary for this release is missing the build settings to include the arm64 architecture.

I was able to rollback to 2.0.1 as a workaround.

```
ld: bitcode bundle could not be generated because '/Users/..../Pods/surveymonkey-ios-sdk/SurveyMonkeyiOSSDK.framework/SurveyMonkeyiOSSDK(SMError.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/..../Pods/surveymonkey-ios-sdk/SurveyMonkeyiOSSDK.framework/SurveyMonkeyiOSSDK' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by doctorcolinsmith** [comment]
I should add that I found this when doing a Product → Archive operation.

**Comment by doctorcolinsmith** [comment]
Confirmed that the error goes away in 2.0.3.  Thanks for getting an update out in short order!

**Comment by benleiken** [comment]
awesome!
