### ISSUE TITLE
respondentDidEndSurvey: respondent always `nil`

### ISSUE THREAD

**Issue by eXhausted** [SurveyMonkey/surveymonkey-ios-sdk#60]
Have this issue in debug build. It always falls with error code 5 after successful survey. Any suggestions?

**Comment by algrid** [comment]
It works for me.

Do you have an Advantage account or higher?

>Usage of the respondent data returned by the SurveyMonkey Feedback SDK requires that you have a Advantage account or higher

**Comment by benleiken** [comment]
@eXhausted @algrid is right, are you on an advantage plan or higher?
