### ISSUE TITLE
UIWebView iOS Deprecated API Usage Warning ITMS-90809

### ISSUE THREAD

**Issue by santiagofm** [SurveyMonkey/surveymonkey-ios-sdk#66]
Starting last week, we started receiving an email form Apple complaining we are using `UIWebView` and that API is now deprecated and will be removed in the future.

After analyzing our dependencies we found `SurveyMonkeySDK` is using this API and not the recommended `WKWebView`. Do you have a timeframe of when this change is going to be implemented?

We use SurveyMonkey to provide core features in our product and we wouldn't want this issue to block future releases.

Thank you,

**Comment by gbejarano01** [comment]
@ayeung This is not as simple as an enhancement, this should be a hot fix that you should be able to implement ASAP. 
What @santiagofm didn't mention is that Apple is telling us that in December they won't accept submissions that include UIWebView APIs any longer.

Please, implement the fix as soon as possible.

Thanks

**Comment by ayeung** [comment]
Good to know.  Will look into this soon.

**Comment by santiagofm** [comment]
Hey @ayeung! do you have any updates! thank you

**Comment by ayeung** [comment]
We're looking into this now, hoping to have a new release soon.

**Comment by simonemanneschi** [comment]
Today apple blocked us application for this issue please fix it as soon as possible!!!

**Comment by gbejarano01** [comment]
@simonemanneschi Has Apple blocked you or sent you a warning after review? I get those warnings on every release, but never blocked us.
Can you please clarify? this is super valuable info to have.

**Comment by simonemanneschi** [comment]
We identified one or more issues with a recent delivery for your app, "Kpet" 1.0.3 (1.0.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - **Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020.** See https://developer.apple.com/documentation/uikit/uiwebview for more information. | We identified one or more issues with a recent delivery for your app, "Kpet" 1.0.3 (1.0.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
-- | --
We identified one or more issues with a recent delivery for your app, "Kpet" 1.0.3 (1.0.0). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by simonemanneschi** [comment]
We tried two times, same results :(

**Comment by gbejarano01** [comment]
`TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020.`

That is a warning, they will still review your app and eventually approve.

Still it would be super nice to get a fix ASAP.

**Comment by simonemanneschi** [comment]
they explicit says Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020 not december 2020

**Comment by gbejarano01** [comment]
@simonemanneschi sorry I copied that from the message they sent us 1 day ago, it's weird, our message says December not April... wondering which one is right.

**Comment by gbejarano01** [comment]
@simonemanneschi I just found [this article](https://developer.apple.com/news/?id=12232019b) that explains it very well

> If your app still embeds web content using the deprecated UIWebView API, we strongly encourage you to update to WKWebView as soon as possible for improved security and reliability. WKWebView ensures that compromised web content doesn’t affect the rest of an app by limiting web processing to the app’s web view. And it’s supported in iOS and macOS, and by Mac Catalyst.

The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

It's only for new apps April, for existing app updates it's December.

**Comment by simonemanneschi** [comment]
It's only for new apps April, for existing app updates it's December.

Thanks! but our is a new App :( i hope survey monkey team will fix it asap @ayeung

**Comment by ayeung-sm** [comment]
2.0.6 is out and should resolve the deprecated webview issue
