### ISSUE TITLE
Control modal presentation style of the feedback view controller

### ISSUE THREAD

**Issue by vrutberg** [SurveyMonkey/surveymonkey-ios-sdk#69]
In iOS 13 Apple introduced a new presentation style when a view controller is modally presented. Seeing as the SDK handles the presentation of the feedback view controller I haven't found a way to control or opt out of this new presentation style. It would be very nice to be able to control the presentation style used.

**Comment by ayeung** [comment]
Thanks for filing this.  Will take a look at enabling this feature as a part of the next release.

**Comment by vrutberg** [comment]
@ayeung Thanks for your quick reply. I'm looking forward to the next release. A problem right now is if the user dismisses the survey using the "drag to dismiss" gesture the completion callback never runs.

Another, slightly related question, is if there is any support for pushing the survey onto a navigation stack, as opposed to presenting it?

**Comment by ayeung** [comment]
Don't believe we currently have support for pushing a survey to the navigation stack.

**Comment by nfox513** [comment]
@ayeung just a ping that this is critical for us as well. The new iOS 13 modal style breaks a core element of the SDK (both an atypical UX for our app as well as no completion callback). Fixing this via modifying the presentation style should be a one-liner, but even better would be a way to push the survey onto the navigation stack however we'd like to.

Would love an ETA on this fix so we can know whether to keep using SurveyMonkey or switch our account to a different provider.

**Comment by ayeung** [comment]
We'll try to get a patch release out sometime next week that is modifying the presentation style.

**Comment by ksubjeck** [comment]
@vrutberg @nfox513 A new version (2.0.5) has just been published to cocoapods with a fix for this issue. Please let us know if there are any problems, thanks!

**Comment by vrutberg** [comment]
Thanks @ksubjeck. I've tested it and it seems to be working well.
