### ISSUE TITLE
SMFeedbackViewController calls optional delegate function and crashes

### ISSUE THREAD

**Issue by micke-b** [SurveyMonkey/surveymonkey-ios-sdk#74]
If I create a `SMFeedbackViewController` like so:

```swift
if let feedbackViewController = SMFeedbackViewController(survey: "LBQK27G") { 
    feedbackViewController.delegate = self
    feedbackViewController.present(from: self, animated: true, completion: nil)
 }
```

And then chose **_not_** to implement the **_optional_** `respondentDidEndSurvey` callback, declared in `SMFeedbackDelegate ` as **_optional_**:

```Objective-C
@protocol SMFeedbackDelegate <NSObject>
@optional
- (void)respondentDidEndSurvey:(SMRespondent *)respondent error:(NSError *) error;
````

The SDK craches my app when pressing the close button on the survey:

`reason: '-[XXXXXX respondentDidEndSurvey:error:]: unrecognized selector sent to instance ...`

If the function is marked optional it should not crash the app if it's not implemented. Either make it non-optional or fix this issue.

**Comment by ksubjeck** [comment]
Hey @micke-b , a new version 2.0.5 has just been published to cocoapods and this function is no longer optional. Please let me know if there are any problems, thanks!

**Comment by micke-b** [comment]
Thanks. :)
