### ISSUE TITLE
Exit Survey Prevention in mobile SDK

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-ios-sdk#77]
Hello everyone,

I am new to surveymonkey, I just noticed that surveymonkey does not have (or I am not aware) a feature that gives a warning whenever a person tries to exit an in-progress survey? Could anyone give a recommendation with this? I don't want my customer to accidentally click exit and have to refill the whole survey.

Please kindly help with this. Thank you

**Comment by ayeung** [comment]
If you're using a fragment to display, you can overwrite the onBackPressed() function in the activity and handle it there.

**Comment by felicianovia** [comment]
Hi Ayeung, 
Thank you for the response. My iOS engineer says that in iOS he does not have fragment and onBackPressed() function. He said these are all in Android. Could you help?

Thank you
