### ISSUE TITLE
Can we use onBackPressed() function for iOS to prevent survey exit?

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-ios-sdk#78]
Hello everyone,

Can we use the onBackPressed() function in iOS?

Thank you

**Comment by ayeung** [comment]
We're using the standard UIBarButtonItem inside SMFeedbackViewController to add a callback for the Cancel Button:
`UIBarButtonItem *menuItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(onCancelPressed)];`

You may able to get it from the view controller and adjust it accordingly.

On another note, respondentDidEndSurvey does return and errorcode of ERROR_CODE_USER_CANCELED when the user hit the cancel button.  However, this does not allow you to overwrite the cancel behavior, only to determine when someone has cancelled.
