### ISSUE TITLE
Linking error with Reachability pod 

### ISSUE THREAD

**Issue by youvalv** [SurveyMonkey/surveymonkey-ios-sdk#8]
Hi

When using cocoapods I get this error:
duplicate symbol _kReachabilityChangedNotification in:
    /Users/youvalvaknin/Library/Developer/Xcode/DerivedData/ios-client-ffhifmubyoilmmdcweeoefxuinsz/Build/Products/Debug-iphoneos/libReachability.a(Reachability.o)
    /Users/youvalvaknin/Development/Source/HelloHeart/Pods/surveymonkey-ios-sdk/SurveyMonkeyiOSSDK.framework/SurveyMonkeyiOSSDK(SMNetworkUtil.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have reachability needed in a different target on a different project in the workspace (added as a pod there)
When adding SurveyMonkey pod to the Main app without Reachability, I get Undefined symbol on the main app.
When adding reachability as well to the main app, I get the above error.

Any way around it? 

Thanks

**Comment by benleiken** [comment]
@youvalv just pushed version 1.0.4, let me know if it fixes your issue. run `pod update`!

**Comment by youvalv** [comment]
Worked like a charm!
