### ISSUE TITLE
Can I prevent a survey responder from exiting the survey using these codes?

### ISSUE THREAD

**Issue by felicianovia** [SurveyMonkey/surveymonkey-ios-sdk#80]
"We're using the standard UIBarButtonItem inside SMFeedbackViewController to add a callback for the Cancel Button:
UIBarButtonItem *menuItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(onCancelPressed)];

You may able to get it from the view controller and adjust it accordingly.

On another note, respondentDidEndSurvey does return and errorcode of ERROR_CODE_USER_CANCELED when the user hit the cancel button. However, this does not allow you to overwrite the cancel behavior, only to determine when someone has cancelled."

Hello everyone, I tried implementing this into my app, but somehow this is behaving differently thatn Android. Right now the warning shows up after I have closed the survey. It works perfectly fine in Android I am wondering if these codes can be used to prevent people from exiting the survey while in the survey?

**Comment by ayeung** [comment]
If you're using the code ERROR_CODE_USER_CANCELED, I already mentioned that it doesn't allow you to modify the cancel behavior.
