### ISSUE TITLE
Using the SimpleSurvey sample app always generates error 5 in the delegate

### ISSUE THREAD

**Issue by youvalv** [SurveyMonkey/surveymonkey-ios-sdk#9]
When testing SimpleSurvey (tried with the given hash, tried with a new hash for a survey I created with a Mobile SDK collector)
- (void)respondentDidEndSurvey:(SMRespondent *)respondent error:(NSError *) error

respondent is always nil and description of error:
```
Error Domain=SurveyMonkeySDK_ServerError 
Code=5 "(null)" 
UserInfo={SurveyMonkeySDK_Error=There was a problem retrieving the user's response to this survey., 
NSUnderlyingError=0x12edb16d0 
{
    Error Domain=NSURLErrorDomain 
    Code=-1002 "unsupported URL" 
    UserInfo=
        {
            NSLocalizedDescription=unsupported URL, NSUnderlyingError=0x12eecda50 
            {
                Error Domain=kCFErrorDomainCFNetwork 
                Code=-1002 "unsupported URL" 
                UserInfo=
                    {
                        NSLocalizedDescription=unsupported URL
                    }
                }
            }
        }
}
```

Using the android SDK, the sample collector returned RESULT_OK and using my collector I got error 7, "Response limit exceeded for your plan. Upgrade to access more responses through the SDK." which makes sense.
Again, using iOS, received error 5 for both hast collectors

**Comment by benleiken** [comment]
@youvalv fixed now, appreciate you finding this!

**Comment by youvalv** [comment]
no need to issue a pod update/

**Comment by benleiken** [comment]
@youvalv yeah, the cocoapod has been updated, pod update should install 1.0.5

**Comment by leapfrog-saugat** [comment]
Hi,

I seem to be having the same problem with Simple Survey sample app for iOS.

**When I change the survey hash from the default value to my own, the `repondent` value is nil and I get server error code 5 and code 7.**

> 2018-01-01 10:25:46.604971+0545 Simple Survey[84422:3060465] Error Domain=SurveyMonkeySDK_ServerError Code=5 "(null)" UserInfo={SurveyMonkeySDK_Error=There was a problem retrieving the user's response to this survey., NSUnderlyingError=0x604000447b90 {Error Domain=SurveyMonkeySDK_ServerError Code=7 "(null)" UserInfo={SurveyMonkeySDK_Error=Response limit exceeded for your plan. Upgrade to access more responses through the SDK.}}}
> 

I have only collected 8 responses at the time of writing so not sure why I am getting code 7. 

The survey responses are being collected in my dashboard though.

- SDK: surveymonkey-ios-sdk (1.0.8)
- Survey Hash: XL7LTCG
- Test environment: Simulator (iPhone 6), Xcode 9.1 (9B55)

**Comment by benleiken** [comment]
@leapfrog-saugat what plan type do you have? SDK Data Pull is only available on Advantage plans and higher. that's what the error message is referring to.

**Comment by leapfrog-saugat** [comment]
@benleiken Thanks for the reply. I am indeed on Free Plan.
